# Makefile for MCP-openMSX project
.PHONY: all clean

# Fall back to npm if pnpm not found
NPM := $(shell which pnpm 2>/dev/null && echo pnpm || echo npm)

ESC = $(shell printf '\033')
COL_WHITE = $(ESC)[1;37m
COL_ORANGE = $(ESC)[1;38:5:208m
COL_RESET = $(ESC)[0m


npm_install:
	@echo "$(COL_WHITE)#### Installing npm dependencies...$(COL_RESET)"
	$(NPM) install

build: npm_install
	@echo "$(COL_WHITE)#### Building MCP-openMSX project...$(COL_RESET)"
	$(NPM) run build

run_stdio: build
	@echo "$(COL_WHITE)#### Running MCP-openMSX project with stdio...$(COL_RESET)"
	node dist/server.js

run_http: build
	@echo "$(COL_WHITE)#### Running MCP-openMSX project with HTTP server...$(COL_RESET)"
	MCP_TRANSPORT=http node dist/server.js

pack: build
	@echo "$(COL_WHITE)#### Packing MCP-openMSX project...$(COL_RESET)"
	cp ../README.md .
	cp ../LICENSE .
	$(NPM) pack

inspector: build
	@echo "$(COL_WHITE)#### Inspecting MCP-openMSX project...$(COL_RESET)"
	DANGEROUSLY_OMIT_AUTH=true npx @modelcontextprotocol/inspector node dist/server.js

publish: build pack
	@echo "$(COL_WHITE)#### Publishing MCP-openMSX project...$(COL_RESET)"
	$(NPM) pack --dry-run
	npm login --registry=https://registry.npmjs.org/
	npm publish --access public --no-git-checks
	npm version patch

info:
	@echo "$(COL_WHITE)#### MCP-openMSX published packet information$(COL_RESET)"
	$(NPM) view @nataliapc/mcp-openmsx

clean:
	rm -rf node_modules
	rm -rf dist
	rm -f package-lock.json
	rm -f README.md
	rm -f LICENSE
	rm -f *.tgz

#Checks

depcheck:
	@echo "$(COL_ORANGE)## depcheck...$(COL_RESET)"
	@depcheck || true

outdated:
	@echo "$(COL_ORANGE)## npm outdated...$(COL_RESET)"
	@$(NPM) outdated || true

npq:
	@echo "$(COL_ORANGE)## npq...$(COL_RESET)"
	@npq --dry-run || true

check: depcheck outdated npq
